name: Create Confluence Page

on:
  push:
    branches:
      - confluence

jobs:
  create-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Image Pull
        run: docker pull lianyuxue1020/kube-scheduler:v1.22.3
