name: Main Workflow

on:
  push:
    branches:
      - mainss

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check 2
        run: curl -s https://github.com/newrelic/nri-flex/tags | grep -o 'tag/[^"]*' | sed 's/tag\///' | head -n 1


