name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      workflow_to_trigger:
        description: 'Select the workflow to trigger'
        required: true
        default: 'workflowA'

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Workflow A
        if: ${{ github.event.inputs.workflow_to_trigger == 'workflowA' }}
        uses: ./.github/workflows/workflowA.yml

      - name: Trigger Workflow B
        if: ${{ github.event.inputs.workflow_to_trigger == 'workflowB' }}
        uses: ./.github/workflows/workflowB.yml
