name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Other steps specific to your main workflow

      - name: Set input for Sub Workflow
        run: echo "SOME_INPUT=Hello, from Main Workflow!" >> $GITHUB_ENV

      - name: Trigger Sub Workflow
        uses: ./.github/workflows/sub_workflow.yml
