name: Main Workflow

on:
  push:
    branches:
      - mainss

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Getting the value for infra
        run: |
          TAG=`cat ./txt1.txt`
          cat txt1.txt
          echo "::set-output name=tagss::$TAG"
          
      - name: calling workflow
        uses: ./github/workflows/workflowA
        with:
          tag: ::set-output name=tagss::$TAG
         
