name: Create Confluence Page

on:
  push:
    branches:
      - confluence
    paths:
      - 'change_folder/**'


jobs:
  merge_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Print Workflow
        run: echo "Merge Task"
      - name: Get the change number
        run: |-
          c_no=$(cat ./change_folder/change_request.txt)
          echo "CR_NO=$c_no" >> $GITHUB_ENV

      - name: Display Change No.
        run: echo "The change number is $CR_NO"

      - name: Read and Process Data
        run: |-
          while IFS= read -r line
          do
            echo "Line: $line"
            IFS=":" read -r key value <<< "$line"
            echo "Key: $key"
            echo "Value: $value"
          done < data.txt        
