name: Create Confluence Page

on:
  push:
    branches:
      - test


jobs:
  merge_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Print Workflow
        run: echo "Merge Task"
      - name: Get the change number
        run: |-
          c_no=$(cat ./change_folder/change_request.txt)
          echo "CR_NO=$c_no" >> $GITHUB_ENV
          #abcd

      - name: Display Change No.
        run: echo "The change number is $CR_NO"

      - name: Read and Process Data
        run: |-
          while IFS= read -r line
          do
            echo "Line: $line"
            IFS=":" read -r key value <<< "$line"
            echo "Key: $key"
            echo "Value: $value"
          done < data.txt        

      - name: Read and Process Data
        run: |-
          while IFS= read -r line
          do
            image_names=$(echo "$line" | grep -oE 'dkr-io/[^ ]+:[0-9]+\.[0-9]+\.[0-9]+')
            echo "Image Names: $image_names"
          done < data.txt

      - name: Install jq
        run: sudo apt-get install jq


      - name: Close Pull Request
        if: github.event_name == 'push' && github.event.before != '0000000000000000000000000000000000000000'
        run: |
          PR_NUMBER=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository }}/test&state=open" | jq -r .[0].number)
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" -d '{"state":"closed"}'
