#Workflow for folder structure - Working ! Manual updation of tag!
name: Folder Change Trigger

on:
  push:
    branches:
      - main  # Replace with your desired branch name if different
permissions:
  contents: write      
      

jobs:
  run_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.        
          

      - name: Get changed folder name
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^..HEAD)
          FOLDER_NAME=$(echo "$CHANGED_FILES" | awk -F/ '{print $1}' | uniq)
          echo "CHANGED_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV

      - name: Display changed folder name
        run: |
          echo "The changed folder is $CHANGED_FOLDER"
          if [ "${CHANGED_FOLDER}" = ".github" ] ; then
            echo "${CHANGED_FOLDER}"
          fi
          

      - name: Get the tag
        id: get_latest_tag
        run: |-
          if ["${CHANGED_FOLDER}" = "infrastructure-k8s"] ; then
            echo "${CHANGED_FOLDER}"
            last_tag=`cat ./${CHANGED_FOLDER}/last_image.txt`
            echo "::set-output name=last_tag::$last_tag"
            echo "${last_tag}"
            released_tag=`cat ./${CHANGED_FOLDER}/released.txt`
            echo "::set-output name=released_tag::$released_tag"
          fi
          

      - name: Docker Pull     
        run: |-
           if ["${CHANGED_FOLDER}" = "infrastructure-k8s"] || ["${CHANGED_FOLDER}" = "nri-kubernetes"] ; then
             if [ "${{ steps.get_latest_tag.outputs.last_tag }}" != "${{ steps.get_latest_tag.outputs.released_tag }}" ]; then
                docker pull newrelic/${CHANGED_FOLDER}:${{ steps.get_latest_tag.outputs.released_tag }}
                echo ${{ steps.get_latest_tag.outputs.released_tag }} > ./${CHANGED_FOLDER}/last_image.txt
                git pull
                git config user.name "rajvaya13"
                git config user.email "raj.vaya2017@gmail.com"
                git add -f ./${CHANGED_FOLDER}/last_image.txt
                git commit -m "Updating the latest image"
                git push -u origin main
             fi
           fi 
