name: Other Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Message
        run: echo "This is the target workflow being triggered!"
