name: Fetch Folder Name
on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  fetch-folder-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for Txt File Changes
        run: |
          for folder in $(git diff --name-only HEAD^..HEAD | grep -oE '^[^/]+/' | sort -u); do
            echo "Folder changed: $folder"
          done
        
