#Workflow for folder structure
name: Folder Change Trigger

on:
  push:
    branches:
      - main  # Replace with your desired branch name if different
permissions:
  contents: write      
      

jobs:
  run_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.        
          

      - name: Get changed folder name
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^..HEAD)
          FOLDER_NAME=$(echo "$CHANGED_FILES" | awk -F/ '{print $1}' | uniq)
          echo "CHANGED_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV

      - name: Display changed folder name
        run: |
          echo "The changed folder is $CHANGED_FOLDER"
          echo "${CHANGED_FOLDER}"

      - name: Get the tag
        id: get_latest_tag
        run: |
          last_tag=`cat ./${CHANGED_FOLDER}/last_image.txt`
          echo "::set-output name=last_tag::$last_tag"
          released_tag=`cat ./${CHANGED_FOLDER}/released.txt`
          echo "::set-output name=released_tag::$released_tag"
