name: Matrix Workflow
on: 
  #workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write      

jobs:
  run_workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: [nri-kubernetes, infrastructure-k8s]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Get the tag
        id: get_latest_tag
        run: |
          last_tag=`cat ./${{ matrix.item }}/last_image.txt`
          echo "::set-output name=last_tag::$last_tag"
          released_tag=`cat ./${{ matrix.item }}/released.txt`
          echo "::set-output name=released_tag::$released_tag"
        
      - name: Check for changes
        id: check_changes
        run: |
          if [ "${{ steps.get_latest_tag.outputs.last_tag }}" == "${{ steps.get_latest_tag.outputs.released_tag }}" ]; then
            echo "::set-output name=skip_job::true"
          fi

      - name: Docker Pull     
        if: matrix.item == 'infrastructure-k8s' && steps.check_changes.outputs.skip_job != 'true'
        run: |-
          docker pull newrelic/${{ matrix.item }}:${{ steps.get_latest_tag.outputs.released_tag }}
          echo ${{ steps.get_latest_tag.outputs.released_tag }} > ./${{ matrix.item }}/last_image.txt
          git pull
          git config user.name "test"
          git config user.email "test@email.com"
          git add -f ./${{ matrix.item }}/last_image.txt
          git commit -m "Updating the latest image"
          git push -u origin main
