name: Fetch Folder Name
on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  fetch-folder-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Fetch last commit hash
        id: fetch-last-commit-hash
        run: |
          last_commit_hash=$(git log -1 --pretty=format:%H)
          echo "::set-output name=last_commit_hash::$last_commit_hash"

      - name: Fetch changed files
        id: fetch-changed-files
        run: |
          last_commit=${{ steps.fetch-last-commit-hash.outputs.last_commit_hash }}
          changed_files=$(git diff --name-only $last_commit HEAD)
          echo "::set-output name=changed_files::$changed_files"

      - name: Extract folder name
        id: extract-folder-name
        run: |
          IFS=$'\n' read -ra files <<< "${{ steps.fetch-changed-files.outputs.changed_files }}"
          for file in "${files[@]}"; do
            folder_name=$(dirname "$file")
            echo "::set-output name=folder_name::$folder_name"
            break
          done

      - name: Display folder name
        run: |
          echo "Changed folder name: ${{ steps.extract-folder-name.outputs.folder_name }}"
