name: CI

on:
  push:
    branches:
      - main


jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed folder name
        run: |
          # Get the list of changed files between the current and previous commit
          CHANGED_FILES=$(git diff --name-only HEAD^..HEAD)

          # Use awk to extract the folder name of the first changed file (assumes the first file is inside a folder)
          FOLDER_NAME=$(echo "$CHANGED_FILES" | awk -F/ '{print $1}' | uniq)

          # Set the output variable for later use
          echo "CHANGED_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV

      - name: Display changed folder name
        run: |
          echo "The changed folder is $CHANGED_FOLDER"
