#Workflow for folder structure
name: MERGE Workflow
on: 
  #workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write      
      

jobs:
  run_workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: [nri-kubernetes, infrastructure-k8s] # Add your lists of itemss heres
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Get the tag
        id: get_latest_tag
        run: |
          last_tag=`cat ./${{ matrix.item }}/last_image.txt`
          echo "::set-output name=last_tag::$last_tag"
          released_tag=`cat ./${{ matrix.item }}/released.txt`
          echo "::set-output name=released_tag::$released_tag"
        
      - name: Docker Pull     
        run: |-
           #tag1=$(curl -s "https://registry.hub.docker.com/v2/repositories/newrelic/${{ matrix.item }}/tags/?limit=1" | jq -r ".results[0].name")

           if [ "${{ steps.get_latest_tag.outputs.last_tag }}" != "${{ steps.get_latest_tag.outputs.released_tag }}" ]; then
              docker pull newrelic/${{ matrix.item }}:${{ steps.get_latest_tag.outputs.released_tag }}
              echo ${{ steps.get_latest_tag.outputs.released_tag }} > ./${{ matrix.item }}/last_image.txt
              git pull
              git config user.name "rajvaya13"
              git config user.email "raj.vaya2017@gmail.com"
              git add -f ./${{ matrix.item }}/last_image.txt
              git commit -m "Updating the latest image"
              git push -u origin main
           fi
