#Workflow for folder structure
name: Matrix Workflow
on: 
  #workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write      
      

jobs:
  run_workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed folder name
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^..HEAD)
          folder=$(echo "$CHANGED_FILES" | awk -F/ '{print $1}' | uniq)
          echo "::set-output name=folder_name::$folder"

      - name: Display changed folder name
        run: |
          echo "The changed folder is $folder_name"

