name: Workflow A

on:
  push:
    branches:
      - main

jobs:
  jobA:
    runs-on: ubuntu-latest

    steps:
      # Steps for Workflow A
      - name: Step 1 of Workflow A
        run: echo "This is step 1 of Workflow A."
 

      - name: Step 2 of Workflow A
        run: echo "This is step 2 of Workflow A."
